name: Churn-Pred-Pipeline
on:
  push:
    branches: [ dev ]
env:
  APPLICATION_NAME: ChurnPipelinev1.2

jobs:
  deploy_to_EKS:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
  runs-on: ubuntu-18.04
  steps:
  - name: Install and configure kubectl
      run: |
      VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
      curl https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl \
          --progress-bar \
          --location \
          --remote-name
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/
      echo ${{ secrets.KUBECONFIG }} | base64 --decode > kubeconfig.yaml

  - name: Deploy
      env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
      export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
      export IMAGE_TAG=${{ env.SHORT_SHA }}
      export KUBECONFIG=kubeconfig.yaml
      envsubst < k8s/kustomization.tmpl.yaml > k8s/kustomization.yaml
      kubectl kustomize k8s | kubectl apply -f -
